name: docker-ci-pipeline
on: push
jobs:
  sysfooci-job:
    runs-on: ubuntu-latest
    steps:
      - name: Code Checkout
        uses: actions/checkout@v6
      - name: Build Image
        run: docker build -t ${{ vars.DOCKERDEMO1 }}/helloworld-demo-python:v1 .
      - name: verify name
        run: docker images
      - name: Docker login
        uses: docker/login-action@v3.6.0
        with:
          username:${{ vars.DOCKERDEMO1 }}
          password:${{ secrets.DOCKER_TOKEN }}
      - name: Push Image
        run: docker push ${{ vars.DOCKERDEMO1 }}/helloworld-demo-python:v1 

          
